#term xterm-256color

scrollback_lines 10000

# Font
font_family      Cascadia Code Light
bold_font        Cascadia Code Regular
italic_font      Cascadia Code Light Italic
bold_italic_font Cascadia Code Italic

font_size 18.0
macos_thicken_font 0.25

# UI
remember_window_size  no
initial_window_width  960
initial_window_height 576

window_margin_width 10
macos_titlebar_color background

# tab bar
tab_title_template "{index}: {title}"
tab_bar_style powerline
active_tab_font_style bold

# key mapping
map ctrl+a>c new_tab
map ctrl+a>n next_tab
map ctrl+a>p previous_tab
map ctrl+a>, set_tab_title
map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5
map ctrl+a>6 goto_tab 6
map ctrl+a>7 goto_tab 7
map ctrl+a>8 goto_tab 8
map ctrl+a>9 goto_tab 9

copy_on_select yes
shell_integration disabled
enable_audio_bell no

# colorscheme
include ./tokyonight-storm.conf

